<?php

namespace Jtrw\DAO\Tests\Src;

use Jtrw\DAO\Tests\DbConnector;

class MysqlObjectTest extends AbstractTestObjectAdapter
{
    public function setUp(): void
    {
        $this->db = DbConnector::getInstance();
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}