<?php

namespace Jtrw\DAO\Tests\Src;

use Jtrw\DAO\Tests\DbConnector;
use PHPUnit\Framework\Assert;

class MysqlObjectTest extends AbstractTestObjectAdapter
{
    public function setUp(): void
    {
        $this->db = DbConnector::getInstance();
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    public function testGetDataBaseType()
    {
        Assert::assertEquals(DbConnector::DRIVER_MYSQL, $this->db->getDatabaseType());
    }
    
    public function testGetTableIndexes()
    {
        $indexes = $this->db->getTableIndexes(static::TABLE_SETTINGS);
        Assert::assertNotEmpty($indexes[0]['Table']);
        Assert::assertEquals($indexes[0]['Table'], 'settings');
    }
}