<?php

namespace Jtrw\DAO\Tests\Src;

use Jtrw\DAO\Tests\DbConnector;
use PHPUnit\Framework\Assert;

class PostgreSqlObjectTest extends AbstractTestObjectAdapter
{
    public function setUp(): void
    {
        $this->db = DbConnector::getInstance(DbConnector::DRIVER_PGSQL);
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    public function testOr()
    {
        Assert::assertTrue(true);
    }
    
    public function testGetDataBaseType()
    {
        Assert::assertEquals(DbConnector::DRIVER_PGSQL, $this->db->getDatabaseType());
    }
    
    public function testMatch()
    {
        Assert::assertTrue(true);
    }
    
    public function testSoundex()
    {
        Assert::assertTrue(true);
    }
    
    public function testDeleteTable()
    {
        Assert::assertTrue(true);
    }
}