<?php

namespace Jtrw\DAO\Tests\Src;

use Jtrw\DAO\DataAccessObjectInterface;
use Jtrw\DAO\Query\Query;
use Jtrw\DAO\Tests\DbConnector;
use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Assert;

class QueryTest extends TestCase
{
    private const TABLE_SETTINGS = "settings";
    
    private DataAccessObjectInterface $db;
    
    public function setUp(): void
    {
        $this->db = DbConnector::getInstance();
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    
    public function testFetch()
    {
        $query = new Query($this->db);
        
        $id = $this->createItem();
        $result = $query->select("caption")
            ->table(static::TABLE_SETTINGS)
            ->where(['id' => $id])
            ->fetch();
        
        Assert::assertEquals($result['caption'], "testQuery");
    }
    
    private function createItem(): int
    {
        $values = [
            'id_parent' => 0,
            'caption'   => 'testQuery',
            'value'     => 'dataTestQuery'
        ];
        $idSetting = $this->db->insert(static::TABLE_SETTINGS, $values);
        Assert::assertIsInt($idSetting);
        return $idSetting;
    }
}