name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker-compose up -d
   
    - name: Fix Permission
      run: make fix-permission
   
    - name: Composer Install
      run: composer install -vvv
    
    - name: Docker ps
      run: docker ps
    
    - name: Wait for MySQL
      run: sleep 15   
    
    - name: Phpunit
      run: docker-compose run --rm --no-deps dao_php sh -lc 'php ./vendor/phpunit/phpunit/phpunit -c ./tests/phpunit.xml --testdox --stderr --coverage-clover $GITHUB_WORKSPACE/clover.xml'
   
    - name: install golangci-lint and goveralls
      run: |
         sh -s -- -b $GITHUB_WORKSPACE v1.44.0
         go get -u github.com/mattn/goveralls

    - name: submit coverage
      run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/clover.xml
      working-directory: backend
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
