name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker-compose up -d
   
    - name: Fix Permission
      run: make fix-permission
   
    - name: Composer Install
      run: composer install -vvv
    
    - name: Phpunit
      run: docker-compose run --rm --no-deps dao_php sh -lc 'php ./vendor/phpunit/phpunit/phpunit -c ./tests/phpunit.xml --testdox --stderr'
    
    - name: Make logs
      run: make logs
